### PR TITLE
Fix exception when using try in a conditional

### LINKED ISSUE #1: TryTiny::RequireCatch fails when using try in a conditional
With the following code, this policy throws an exception because there's no next sibling:
```perl
#!/usr/bin/env perl

use Try::Tiny;

my $x = {};
if ( !try { $x->isa('Foo') } ) {
    print "Not a Foo.\n";
}
```

Error:
```
brianc64 ok % perlcritic --single-policy TryTiny::RequireCatch  example.pl
Fatal error while critiquing "example.pl": Can't call method "content" without a package or object reference at /usr/local/cpanel/3rdparty/perl/524/lib64/perl5/cpanel_lib/Perl/Critic/Policy/TryTiny/RequireCatch.pm line 56.
```

### PR DESCRIPTION
**Pull request by bk2204**
This fixes #1.

### CODE REVIEW

**Comment by Flimm** [comment]
Thanks. I'm not a member of the Lokku organisation on GitHub any more, how would @lokku like to proceed? @kaoru @mtmail

**Comment by kaoru** [comment]
Sadly I'm no longer with Lokku and the company such as it exists now doesn't use Perl.

@bk2204 the change looks good to me! Can I suggest you fork Perl::Critic::Lokku it and release it to CPAN under a new name?

Maybe @Flimm (who still has ownership of the namespace on CPAN) could release a final version that adds a note in the docs that the module has been replaced by whatever you call yours.

Thanks!

**Comment by bk2204** [comment]
This isn't terribly critical to me at the moment.  We happened to trigger it because we had a mismatch between our lint tool and the version of perlcritic that it used, and it accidentally enabled this rule.

We do use the ProhibitExitingSubroutine rule, so it's possible I'll pick this up and release a new version to CPAN.  I'll report back if I do.

**Comment by Flimm** [comment]
I've released a new version 0.003 on CPAN with this fix: https://metacpan.org/pod/Perl::Critic::Lokku

As I don't have access to this GitHub repo any more, I can't merge in the changes.

I've included a notice saying that the module is abandoned.

If anyone from @lokku would like to move Perl::Critic::Lokku to their PAUSE account, let me know.

**Pull request merged**
